baseURL = "https://harkerdev.github.io/"
languageCode = "en-us"
title = "Harker Dev"
canonifyURLs = true
pygmentsUseClassic=false
pygmentsCodeFences=true
pygmentsCodeFencesGuessSyntax=true
pygmentsUseClasses=true

theme = "harkerdev"

[params]
    portrait = "img/logo.png"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Join"
  url = "/join/"
  weight = 2

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/HarkerDev/"
  weight = 3